import { CalendarDays, CreditCard, ReceiptText, X } from 'lucide-react';

const money = new Intl.NumberFormat('vi-VN', { style: 'currency', currency: 'VND' });
const date = new Intl.DateTimeFormat('vi-VN', { dateStyle: 'medium', timeStyle: 'short' });

export default function PaymentOrderDetailsModal({ order, onClose }) {
  if (!order) return null;

  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/55 p-4" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><section role="dialog" aria-modal="true" aria-labelledby="order-details-title" className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-3xl bg-white shadow-2xl"><header className="flex items-start justify-between border-b border-slate-100 p-6"><div><p className="text-sm font-semibold text-primary">Order ID: {order.orderId}</p><h2 id="order-details-title" className="mt-1 text-2xl font-bold text-slate-900">Order details</h2></div><button type="button" onClick={onClose} aria-label="Close order details" className="rounded-xl p-2 text-slate-400 transition hover:bg-slate-100 hover:text-slate-700"><X size={21} /></button></header>
    <div className="space-y-6 p-6"><div className="grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-slate-50 p-4"><CalendarDays className="text-primary" size={19} /><p className="mt-2 text-xs font-semibold uppercase tracking-wide text-slate-400">Payment date</p><p className="mt-1 text-sm font-semibold text-slate-700">{date.format(new Date(order.paidAt))}</p></div><div className="rounded-xl bg-slate-50 p-4"><CreditCard className="text-primary" size={19} /><p className="mt-2 text-xs font-semibold uppercase tracking-wide text-slate-400">Payment method</p><p className="mt-1 text-sm font-semibold text-slate-700">{order.paymentMethod}</p></div><div className="rounded-xl bg-success/5 p-4"><ReceiptText className="text-success" size={19} /><p className="mt-2 text-xs font-semibold uppercase tracking-wide text-slate-400">Status</p><p className="mt-1 text-sm font-semibold text-success">{order.status === 'Success' ? 'Successful' : order.status}</p></div></div>
      <div><h3 className="font-bold text-slate-900">Courses</h3><div className="mt-3 divide-y divide-slate-100 overflow-hidden rounded-2xl border border-slate-100">{order.items.map((item) => <div key={item.paymentId} className="flex flex-col justify-between gap-3 p-4 sm:flex-row sm:items-center"><div><p className="font-semibold text-slate-800">{item.title}</p>{item.coupon && <p className="mt-1 text-xs font-medium text-success">Voucher {item.coupon.code} · {item.coupon.discountPercent}% off</p>}</div><strong className="text-primary">{money.format(item.amount)}</strong></div>)}</div></div>
      <div className="rounded-2xl bg-slate-900 p-5 text-white"><div className="flex items-center justify-between gap-4"><span className="text-sm text-white/70">Total paid</span><strong className="text-xl">{money.format(order.total)}</strong></div>{order.transactionNo && <div className="mt-4 border-t border-white/10 pt-4"><p className="text-xs uppercase tracking-wide text-white/50">VNPay transaction ID</p><p className="mt-1 break-all text-sm font-medium">{order.transactionNo}</p></div>}</div>
    </div><footer className="flex justify-end border-t border-slate-100 px-6 py-4"><button type="button" onClick={onClose} className="rounded-xl bg-slate-900 px-5 py-2.5 text-sm font-bold text-white">Close</button></footer></section></div>;
}
